# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f7f07f75beede67788cb1e225181f6aee1cf52351d7dea5470faf56e58c1426eba0b8674429706a67f200c1ed55b67219b811c9796a3746d94cb6cc521b7d79

test:
  secret_key_base: 3f9b4ee8efea7a85d870703dd0297479df98e3c76e09e2859b4e986e314cef36bb1a1bf0962216012b7d23d398ebaec2e95e666b196b46d77014d47af6170a12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
